[settings]
  ID = "cncf-contributor-strategy"

[build]
  base = "website"
  publish = "website/public"
  command = "hugo build"

[build.environment]
  HUGO_VERSION = "0.75.1-ext"

[context.branch-deploy]
  command = "make docs BASEURL_FLAG=\"-b $DEPLOY_PRIME_URL\"/"
  
[context.deploy-preview]
  command = "make docs BASEURL_FLAG=\"-b $DEPLOY_PRIME_URL\"/"